version: 2.1
jobs:
    build-test-publish:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install semantic-release @semantic-release/exec pkg --save-dev
            - run: npm install
            - run: npm test
            - run: npx semantic-release
    build-test:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
    build-test-from-fork:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
workflows:
    version: 2.1
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-publish:
                context: SNYK

    build-test-publish:
        jobs:
            - build-test-publish:
                context: SNYK
                filters:
                    branches:
                        only:
                            - master
    build-test:
        jobs:
            - build-test:
                context: SNYK
                filters:
                    branches:
                        ignore:
                        - master
                        - /pull\/[0-9]+/
            - build-test-from-fork:
                filters:
                    branches:
                        only:
                        - /pull\/[0-9]+/

